#!/usr/bin/env bash
wget -O ukrepeaters.csv https://www.ukrepeater.net/csvcreate.php
python3 csv-convert.py ukrepeaters.csv gb7wl gb7hr 
echo Converted ukrepeaters_conv.csv saved as channels.csv
mv ukrepeaters_conv.csv channels.csv

